#!/bin/sh

# $1 = previous HEAD, $2 = new HEAD, $3 = 1 for branch checkout, 0 for file checkout
[ "$3" = "1" ] || exit 0
[ "$1" != "$2" ] || exit 0

if docker info >/dev/null 2>&1; then
    ./vendor/bin/sail artisan boost:update --ansi
else
    php artisan boost:update --ansi
fi
