<?php

use App\Enums\DestructionReportType;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('destruction_reports', function (Blueprint $table) {
            // Existing reports all account for zaakdata; the Eventloket-data
            // report is the new one.
            $table->string('type')->default(DestructionReportType::Zaakdata->value)->after('destruction_list_id');
        });

        Schema::table('destruction_reports', function (Blueprint $table) {
            // An Eventloket-data report is generated by a nightly command, so
            // there is no coordinator who confirmed it.
            $table->string('coordinator_name')->nullable()->change();
            $table->string('destruction_method')->nullable()->change();
        });
    }

    public function down(): void
    {
        Schema::table('destruction_reports', function (Blueprint $table) {
            $table->dropColumn('type');
        });

        Schema::table('destruction_reports', function (Blueprint $table) {
            $table->string('coordinator_name')->nullable(false)->change();
            $table->string('destruction_method')->nullable(false)->change();
        });
    }
};
