name: PestPHP unit Tests
on: 
  pull_request:
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: tests
          MYSQL_USER: eventloket
          MYSQL_PASSWORD: eventloket
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install PHP versions
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
        coverage: none

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 21

    - name: Install NodeJS dependencies
      run: |
        npm install

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Prepare application
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan passport:keys 
        npm run build
    - name: Execute tests via PestPHP
      env:
        APP_ENV: testing
        DB_CONNECTION: mysql
        DB_DATABASE: tests
        DB_USERNAME: eventloket
        DB_PASSWORD: eventloket
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
      run: vendor/bin/pest